# Generated by Django 6.0.1 on 2026-02-05 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SUV & Sedan, All Party Buses', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vehicle name/title', max_length=200)),
                ('description', models.TextField(help_text='Describe the vehicle, its features, etc.')),
                ('passenger_capacity', models.IntegerField(help_text='How many passengers can this vehicle hold?', validators=[django.core.validators.MinValueValidator(1)])),
                ('show_pricing', models.BooleanField(default=False, help_text="Check to show price, uncheck to show 'Request Quote'")),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per hour/day (optional)', max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, help_text="e.g., 'per hour', 'per day', 'starting at'", max_length=50)),
                ('featured_image', models.ImageField(help_text='Main photo shown on fleet page', upload_to='fleet/featured/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this vehicle from the website')),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Which category does this vehicle belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='travelApp.vehiclecategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fleet/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image description', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order in gallery')),
                ('vehicle', models.ForeignKey(help_text='Which vehicle does this image belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travelApp.vehicle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('duration', models.CharField(choices=[('1', '1 Hour'), ('2', '2 Hours'), ('3', '3 Hours'), ('4', '4 Hours'), ('6', '6 Hours'), ('8', '8 Hours'), ('full-day', 'Full Day (12 Hours)'), ('custom', 'Custom Duration')], max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='travelApp.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'status'], name='travelApp_b_date_601608_idx'), models.Index(fields=['confirmation_code'], name='travelApp_b_confirm_0c919a_idx')],
            },
        ),
    ]
